### ISSUE TITLE
Export bucket discussion

### ISSUE THREAD

**Issue by astib** [EarthCubeInGeo/resen#41]
The discussion included the following key points - 
1. /work will no longer be a mount location
2. Users will be able to export the entire image
3. They should copy whatever data and scripts they need to export in the main bucket (and NOT mount)
4. Anything that is not in mount will be exported
5. Tutorials will be part of the image itself, and not be part of mount as it is currently. 

Issues to figure out with this - 
1. Can we export environmental variables with the image? 
2. Which Docker command will do the job?
3. How will this new set up work with the server?

**Comment by pmreyes2** [comment]
I have tested the following workflow (I believe, as discussed in the meeting), and it might be what we need:

1. Commit the changes from the current bucket (docker container) into a new image name
`$ docker commit bucket_name new_image_name`
2. Save the new image to a file
`$ docker save -o save_bucket.tar new_image_name`
3. Remove the newly created image ( just to test that its not there when we load it again)
`$ docker rmi new_image_name`
4. Load the saved image from the previously created file
`$ docker load -i save_bucket.tar`
The last command will restore the docker image with the same name given to it, in this case : new_image_name:latest , since I didn't put any tags to it. We could use earthcubeingeo/resen-core:SOME_TAG

The original image that I use was the no-conda version (about 3.62 GB) then I put some hdf5 file and a notebook in a container using that image. Finally I commit the changes to a new image (about 3.64 GB). The file and notebook that I drag and drop into the jupyter lab weigh about 17 MB. The saved tar file was about 3.69 GB.

**Comment by asreimer** [comment]
This comment serves to summarize the technical bits of how to accomplish a bucket export/import at a docker container level. It also includes a summary of results of testing done so far:

## Methods
There are 2 different ways to export a docker container so that it can be shared with others:
1) using `docker export` and `docker import`
2) using `docker commit`, `docker save`, and `docker load`

### Method 1
* Using `export`, directly exports the container to a file. The file contains an "image" of the container. Import loads this file into docker as an image.
* No extra storage space is used beyond what is expected. If you have a 5 GB container, the exported file will be 5 GB (or less if compressed) and docker does not use additional hard drive space.
* None of the environment variables in the container are saved to the exported file, so one needs to manually export these themselves. The environment variables can be added to the image during `import` using the `--change` switch.

This method has not been tested by manually exporting environment variables and then retaining them on import using the `--change` switch, so we have no idea how hard this is to do or how well it works.

### Method 2
* `commit` creates an image of the container that one wishes to export. This means that in addition to the N GB of space that the container is consuming on top of the base image it was created from, the new image consumes an additional N GB of space. So compared to `docker export`, `docker commit` and then `docker save` uses an additional N GB of hard drive space.
* `save` exports a docker image to a file. This command retains all environment variables.
* `load` imports an image from a file into docker. Testing revealed that if the imported image depends on image layers that a user already has (say a resen-core image) then the only spaced used up by the import will be from layers

Testing by @ljlamarche showed that N GB of extra space is used doing method 2 compared to method 1. N is the number of GB of stuff a user has added to their container.

### Suggested Modifications to Method 2
One idea to reduce hard drive space usage during the commit and save process was to delete the container after a successful commit and then create a new container from the committed image.

This would work well, so long as a user never performed additional commit and saves, because each commit makes a new layer. This could become a problem if old layers have data files in them that are deleted in subsequent layers. The data files still persist in the old layers, so the image size just keeps growing and the hard drive space isn't freed. There is an experimental feature in docker that might help with this, but it isn't enabled by default and I don't think we should use experimental features in production code. I mention it only so we are aware it exists:

    docker image build --squash

https://docs.docker.com/engine/reference/commandline/image_build/

**Comment by asreimer** [comment]
I did some testing using `docker export`:

1) Used the new resen-core, based on ubuntu and not using conda, the image size is 5.15GB
2) created a container and jumped in as root user: `docker run -it --name resen_testing --user root resen/testing bash`
3) listed the environment variable in the container with `env` then exited
4) exported the container: `docker export resen_testing > test.tar` (the test.tar file ends up being 4.2GB, if gzipped, 1.8GB)
5) imported the exported file as a new image: `cat test.tar | docker import - bigfiletesting:imported`. The imported image size was 4.29GB. You can import a gzipped file too.
6) fire up the new image as a container: `docker run -it --name imported_test bigfiletesting:imported bash` and then listed the envs

### ENVS before export

    SD_RADAR=/home/jovyan/cache/radar.dat
    SHELL=/bin/bash
    TERM=xterm-256color
    MPLBACKEND=Agg
    SD_HDWPATH=/home/jovyan/cache/hdw.dat

### ENVS after importing

    TERM=xterm


### Suggested Workflow
All of these environment variables should set using `/etc/profile` or `/home/jovyan/.bashrc` or something like that anyway. It is probably not great for us to rely on the `ENV` command in the Dockerfiles since no one outside of docker, say running a linux system or macOS, is able to use an ENV command to set environment variables needed by their software. Instead, we should set them explicitly when a shell is started by sourcing the appropriate files.

Also, by default, the imported image will start as the root user. What we want instead is to start as jovyan by default, but this is easy to fix, simply do:

    cat test.tar | docker import --change 'USER jovyan' --change 'WORKDIR /home/jovyan' --change 'ENTRYPOINT ["tini", "-g", "--"]' - bigfiletesting:imported

Then, running:

    docker run -it --name imported_test bigfiletesting:imported bash

starts up the container as jovyan in that user's home directory as expected. So if the environment variables we care about having set were simply set in `/home/jovyan/.bashrc` everything works perfectly.

### Summary
`docker export` and `docker import` are a viable alternative to `commit`, `save`, `load` as long as we:
1) stop relying on the `ENV` command in Dockerfiles and instead set environment variables in file, like one would do on their own linux/macOS machine (either way, we should definitely stop doing this), and
2) set the `ENTRYPOINT`, `USER`, and `WORKDIR` docker instructions during `docker import`. This requires either:
    **a)** a metadata file packaged with the exported container,
    **b)** a file that we package inside of our images that contains this information, then the import would be more like: import the image, start up a container with it, read out the contents of the file, delete the image, and then use the info to re-import the image.

**Comment by asreimer** [comment]
An important design consideration that we (or at least I) didn't properly consider was:
"What happens when a user imports/loads several buckets?"

If a user has imported/loaded say 5 buckets, then using `commit`,`save`,`load` is the best way to go. This is because using `export`/`import` destroys all information about which "base image" the image is built on. So if all 5 buckets all used the same `resen-core` base image, which is ~5GB in size, then using `commit`,`save`,`load` will save 20 GB of space since each `load`ed bucket will use the same base image. `export`/`import` doesn't know anything about base images, so you will need 25 GB of space, jsut for the "base image" level of data contained in each `import`ed image.

I believe this consideration makes it clear that `commit`,`save`,`load` is objectively the best methodology, despite the extra "N GB" of space consumed by the `commit` command. This is somewhat mitigated by the design decision to tell users to mount in data (instead of saving directly to the bucket) if they anticipate requiring a large (more than ~10-20 GB) of data will be needed.

**Comment by ljlamarche** [comment]
Important points from yesterday's discussion:
- Export/import of image WILL be done with `commit`,`save`,`load`
- A resen "bucket" will now consist of 3 things: the image, all mounts, and metadata/set up instructions
- Users should be given the option to only include some of their mounts in the exported bucket
- Check the disk space available on the system before attempting to export and generate an error if there's not enough space
- In the future, may also allow users to exclude specific files/directories from within their mount directories - this should be straight forward with standard tar methods

**Export Bucket:**
1. Record a meta data file listing the mounts
2. Use `commit`->`save` to create a tar file containing the image (image will differ from `resen-core` if user has installed any new packages or configured anything specifically)
3. Create tar files for each mounted directory
4. Generate a single tar file that includes the image tar, mount tars, and the metadata

**Import Bucket:**
1. Untar resen tar file
2. Read metadata file
3. Restore image with `load`
4. Untar mount directories
5. Start a container with the mounted directories configured as specified in the metadata file
6. [Optional] Do other set-up things as required by the metadata file

**Comment by ljlamarche** [comment]
FYI, this appears to be a problem we're having: docker/docker-py#2097
The time-out was happening trying to save just the base image, no added giant data files or anything like that.  I've addressed it by setting the time out to 300 s  in the initialization of `DockerHelper`, which seems to work, but I'm not sure if it'll cause issues with other things down the line.
```
self.docker = docker.from_env(timeout=300)
```
Any thoughts/concerns?
